services:
  kasmos-desktop:
    image: kasmweb/kasmos-desktop:1.17.0
    ports:
      - "6901:6901"
    environment:
      VNC_PW: password
    shm_size: 512m
    stdin_open: true
    tty: true
    restart: unless-stopped
